name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v5

      # Step 2: Set up Node.js environment
      - name: Set up node_modules
        uses: actions/setup-node@v5

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install 

      # Step 4: Run tests
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Run tests
        run: npm test -- --passWithNoTests
      - name: List files in the repository
        run: ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."
